In [4]:
import torch
import torch.nn as nn

In [7]:
# Create model class


class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1) # input -> number of features and output -> how many featues are going through it (5,1)
        self.sigmoid = nn.Sigmoid() # activation function

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out) # Apply sigmoid to the output of the linear layer
        return out # Return the output after sigmoid

In [9]:
## creating dataset
features = torch.rand(10,5)

## create model
model = Model(features.shape[1])

## call model for forword pass
model(features)


tensor([[0.3724],
        [0.3882],
        [0.3770],
        [0.3893],
        [0.3612],
        [0.4233],
        [0.3597],
        [0.4247],
        [0.3931],
        [0.4135]], grad_fn=<SigmoidBackward0>)

In [11]:
 ## show model weights and bias
 model.linear.weight

Parameter containing:
tensor([[ 0.0873, -0.0051,  0.1946, -0.1572, -0.2763]], requires_grad=True)

In [12]:
!pip install torchinfo

In [14]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [23]:
## creating nn with 5 input weights 3 hidden layer and output layer
## 18 weights 4 bias
## we apply relu in hidden layer and in output we apply sigmoid

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3) # input -> number of features hidden layer is getting(5) and output() -> how many featues are going through(3)
        self.relu = nn.ReLU() # activation function
        self.linear2 = nn.Linear(3,1) # getting 3 features as input, as output 1 features is passing through it
        self.sigmoid = nn.Sigmoid() # activation function

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out) # Apply relu to the output of the linear layer
        out = self.linear2(out)
        out = self.sigmoid(out) # Apply sigmoid to the output of the linear layer
        return out # Return the output after sigmoid


In [24]:
## creating dataset
features = torch.rand(10,5)

## create model
model = Model(features.shape[1])

## call model for forword pass
model(features)


tensor([[0.3155],
        [0.2976],
        [0.3157],
        [0.3311],
        [0.2797],
        [0.3131],
        [0.3291],
        [0.3254],
        [0.3060],
        [0.2822]], grad_fn=<SigmoidBackward0>)

In [25]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3764, -0.3976,  0.1549, -0.1924, -0.0856],
        [ 0.3658,  0.0490, -0.1129, -0.1132, -0.1119],
        [-0.1701,  0.3396,  0.3243,  0.2698,  0.1723]], requires_grad=True)

In [27]:
model.linear2.weight

Parameter containing:
tensor([[-0.0839, -0.2524, -0.4339]], requires_grad=True)

In [19]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [28]:
## doing this with help of container

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        return self.network(features)


In [29]:
## creating dataset
features = torch.rand(10,5)

## create model
model = Model(features.shape[1])

## call model for forword pass
model(features)


tensor([[0.4118],
        [0.3989],
        [0.3660],
        [0.3539],
        [0.3803],
        [0.3805],
        [0.3946],
        [0.3762],
        [0.3826],
        [0.3659]], grad_fn=<SigmoidBackward0>)

In [ ]:
##