In [23]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [25]:
df.drop(columns=["id","Unnamed: 32"], inplace=True)

In [26]:
df.shape

(569, 31)

In [27]:
df.head(10)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   
5         M        12.45         15.70           82.57      477.1   
6         M        18.25         19.98          119.60     1040.0   
7         M        13.71         20.83           90.20      577.9   
8         M        13.00         21.82           87.50      519.8   
9         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   
5         0.2087  ...         15.47          23.75           103.40   
6         0.1794  ...         22.88          27.66           153.20   
7         0.2196  ...         17.06          28.14           110.60   
8         0.2350  ...         15.49          30.73           106.20   
9         0.2030  ...         15.09          40.68            97.65   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   
5       741.6            0.1791             0.5249           0.5355   
6      1606.0            0.1442             0.2576           0.3784   
7       897.0            0.1654             0.3682           0.2678   
8       739.3            0.1703             0.5401           0.5390   
9       711.4            0.1853             1.0580           1.1050   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  
5                0.1741          0.3985                  0.12440  
6                0.1932          0.3063                  0.08368  
7                0.1556          0.3196                  0.11510  
8                0.2060          0.4378                  0.10720  
9                0.2210          0.4366                  0.20750  

[10 rows x 31 columns]

In [28]:
X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]


In [29]:
X_train, X_test, y_train , y_test = train_test_split(X,y, test_size=0.2, random_state=42)

## Apply StandarScaler to the columns , mean -->0 , SD --> 1


In [30]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [31]:
X_train,X_test

(array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
          2.09724217,  1.88645014],
        [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
          1.89116053,  2.49783848],
        [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
          0.59760192,  0.0578942 ],
        ...,
        [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
         -0.70863864, -1.27145475],
        [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
          0.43432185,  1.21336207],
        [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
         -0.3345212 , -0.84628745]]),
 array([[-0.4877952 , -0.25088379, -0.46378664, ..., -0.21989091,
          0.23083947,  0.17173277],
        [ 1.37325734,  0.36318719,  1.29254295, ...,  0.93019499,
         -0.58958803, -0.972629  ],
        [ 0.37225845, -0.05148067,  0.38772954, ...,  0.52157274,
         -0.08280128, -0.21536971],
        ...,
        [-0.76105639, -1.08248546, -0.76208585, ..., -

## applying label encoding to the y_train , y_test


In [32]:
encode = LabelEncoder()
y_train = encode.fit_transform(y_train)
y_test = encode.fit_transform(y_test)

In [33]:
y_train,y_test

(array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 

## Converting numpy array to PyTorch array

In [44]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [45]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining model

In [46]:
class MySimpleNN():

  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad=True) ## initilize the weight of dim 30*1 randomely
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True) ## bias with 1 neuron

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss



## defining parameters

In [47]:
learning_rate =  0.1
epochs = 50



## defining training pipelines

In [48]:
#  creating model
model = MySimpleNN(X_train_tensor)
model.weights

tensor([[0.1472],
        [0.7973],
        [0.4446],
        [0.8993],
        [0.3953],
        [0.9137],
        [0.8708],
        [0.3227],
        [0.7041],
        [0.6543],
        [0.0136],
        [0.2872],
        [0.7181],
        [0.6044],
        [0.9833],
        [0.1557],
        [0.4704],
        [0.4155],
        [0.4669],
        [0.0819],
        [0.4964],
        [0.7386],
        [0.8923],
        [0.5333],
        [0.5222],
        [0.0751],
        [0.4211],
        [0.4861],
        [0.6123],
        [0.1244]], dtype=torch.float64, requires_grad=True)

In [49]:
model.bias


tensor([0.], dtype=torch.float64, requires_grad=True)

## Training a model

In [50]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.2672650848132703
Epoch: 2, Loss: 3.1394482428379784
Epoch: 3, Loss: 3.006535148017544
Epoch: 4, Loss: 2.869379576387862
Epoch: 5, Loss: 2.7259166773451637
Epoch: 6, Loss: 2.5759019963096526
Epoch: 7, Loss: 2.4241807001416924
Epoch: 8, Loss: 2.266603273517211
Epoch: 9, Loss: 2.1106027113311643
Epoch: 10, Loss: 1.9613034860082539
Epoch: 11, Loss: 1.8157222121003995
Epoch: 12, Loss: 1.676960639942217
Epoch: 13, Loss: 1.5490569911320102
Epoch: 14, Loss: 1.4325389200194458
Epoch: 15, Loss: 1.323476532265568
Epoch: 16, Loss: 1.2256272295479982
Epoch: 17, Loss: 1.1391026646724285
Epoch: 18, Loss: 1.066855764774031
Epoch: 19, Loss: 1.0078224438242722
Epoch: 20, Loss: 0.9604303111926463
Epoch: 21, Loss: 0.9228112508629022
Epoch: 22, Loss: 0.893035026687702
Epoch: 23, Loss: 0.8693039412477715
Epoch: 24, Loss: 0.8500801338797925
Epoch: 25, Loss: 0.8341418745613092
Epoch: 26, Loss: 0.8205792495388513
Epoch: 27, Loss: 0.808749710787634
Epoch: 28, Loss: 0.7982171663147939
Epoch: 29

In [51]:
model.weights

tensor([[ 0.1892],
        [-0.0888],
        [ 0.2387],
        [-0.1993],
        [ 0.3086],
        [-0.1747],
        [-0.0012],
        [ 0.2282],
        [-0.1528],
        [ 0.2716],
        [ 0.2145],
        [ 0.0197],
        [-0.1136],
        [-0.0998],
        [-0.1744],
        [-0.1990],
        [-0.0633],
        [ 0.0251],
        [ 0.3777],
        [ 0.0677],
        [ 0.0893],
        [ 0.2705],
        [-0.4793],
        [ 0.3371],
        [-0.1221],
        [-0.1937],
        [ 0.1311],
        [-0.2650],
        [-0.0154],
        [-0.0037]], dtype=torch.float64, requires_grad=True)

In [52]:
model.bias

tensor([-0.3192], dtype=torch.float64, requires_grad=True)

## Model evaluation

In [53]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6228070259094238
