In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
## Using Empty
torch.empty(3,4)

tensor([[-8.9762e-07,  4.4528e-41, -8.9762e-07,  4.4528e-41],
        [ 6.8485e-34,  0.0000e+00,  6.8485e-34,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  6.8485e-34,  0.0000e+00]])

In [4]:
## Type
x = torch.empty(2,2)
print(type(x))

<class 'torch.Tensor'>


In [5]:
## Using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
## Using one
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
## using rand
torch.rand(3,3)

tensor([[0.1385, 0.5412, 0.4141],
        [0.3689, 0.0991, 0.8889],
        [0.3755, 0.4302, 0.8469]])

In [8]:
## manual_seed()
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [9]:
## using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
I = torch.eye(3)  # 3x3 identity matrix
print(I)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [11]:
F = torch.full((2, 3), 7)  # 2x3 tensor filled with 7s
print(F)


tensor([[7, 7, 7],
        [7, 7, 7]])


In [12]:
L = torch.linspace(1, 10, 5)  # 5 values between 1 and 10
print(L)


tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


## Shapes in Tesnor

In [13]:
x = torch.tensor([[3,4,5],[4,7,8]])
x

tensor([[3, 4, 5],
        [4, 7, 8]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
## empty_like --> give same shape as you give in input
torch.empty_like(x)

tensor([[              0,       140768640,       117308432],
        [136475499446736,               0,               0]])

In [16]:
## zeros_like --> give 0 to all values

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

## Tensor Data Types



In [17]:
x.dtype
## finding data type

torch.int64

In [18]:
## assign data type
torch.tensor([1.2,2.2,3.3,4.4],dtype=torch.int64)

tensor([1, 2, 3, 4])

In [19]:
torch.tensor([1, 2, 3, 4],dtype=torch.float64)

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [20]:
## using to ()--> changing data type of exesting one
x.to(torch.float32)

tensor([[3., 4., 5.],
        [4., 7., 8.]])

##
Math operation in Tensor

In [21]:
a = torch.rand(3,3)
a

tensor([[0.7041, 0.5573, 0.6959],
        [0.9849, 0.2924, 0.4823],
        [0.6150, 0.4967, 0.4521]])

## 1. Scalar operation

In [22]:
## add
a + 5

## sub

a-5

## mul
a * 5

## int div

a / 5

## Mod

((a * 100)//3)%3

## power

a**2

tensor([[0.4957, 0.3105, 0.4842],
        [0.9701, 0.0855, 0.2326],
        [0.3782, 0.2467, 0.2044]])

In [23]:
p = torch.tensor([1,-2,-3,55])
p

tensor([ 1, -2, -3, 55])

In [24]:
## Abs
torch.abs(p)

tensor([ 1,  2,  3, 55])

In [25]:
## negative
torch.negative(p)

tensor([ -1,   2,   3, -55])

In [26]:
y  = torch.tensor([2.2,3.5,4.5,6.7])
y

tensor([2.2000, 3.5000, 4.5000, 6.7000])

In [27]:
## round --> rounding the values
torch.round(y)

tensor([2., 4., 4., 7.])

In [28]:
## ceil
torch.ceil(y)

tensor([3., 4., 5., 7.])

In [29]:
## floor
torch.floor(y)

tensor([2., 3., 4., 6.])

In [30]:
## clamp

torch.clamp(y , min= 2 , max = 3)

tensor([2.2000, 3.0000, 3.0000, 3.0000])

## Reduction Operation

In [31]:
t = torch.randint(size=(3,3), low=1, high=10)
t

tensor([[4, 8, 6],
        [6, 6, 3],
        [2, 8, 7]])

In [32]:
## sum
torch.sum(t)

tensor(50)

In [33]:
## sum along columns
torch.sum(t,dim=0)

tensor([12, 22, 16])

In [34]:
## sum along row
torch.sum(t,dim=1)

tensor([18, 15, 17])

In [35]:
## Mean
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
r = torch.randint(size=(3,2), low = 1 , high = 15, dtype=torch.
                  float32)
r

tensor([[ 3., 14.],
        [ 3., 11.],
        [ 9.,  8.]])

In [36]:
torch.mean(r)

tensor(8.)

In [37]:
## median
torch.median(r)

tensor(8.)

In [38]:
## product of element
torch.prod(r)

tensor(99792.)

In [39]:
## Standard D

torch.std(r)

tensor(4.3818)

In [40]:
## argmax --> give index of the maximum value
torch.argmax(r)

tensor(1)

In [41]:
## argmin --> give index of min value
torch.argmin(r)

tensor(0)

## Matrix operations


In [42]:
u = torch.randint(size=(3,3), low=1, high=10)
v = torch.randint(size=(3,3), low=1, high=10)


In [43]:
u

tensor([[5, 5, 7],
        [6, 5, 2],
        [5, 7, 9]])

In [44]:
v

tensor([[3, 1, 1],
        [3, 5, 3],
        [2, 9, 3]])

In [45]:
torch.matmul(u,v)

tensor([[ 44,  93,  41],
        [ 37,  49,  27],
        [ 54, 121,  53]])

In [46]:
## Transpose ==> swap dim 0 with dim 1
torch.transpose(v,0,1)

tensor([[3, 3, 2],
        [1, 5, 9],
        [1, 3, 3]])

In [47]:
w = torch.randint(size=(3,3), low = 1 , high = 15, dtype=torch.
                  float32)
w

tensor([[11., 12., 13.],
        [ 4., 12.,  9.],
        [ 4.,  7.,  1.]])

In [48]:
## Determinant

torch.det(w)

tensor(-437.)

In [49]:
## inverse
torch.inverse(w)

tensor([[ 0.1167, -0.1808,  0.1098],
        [-0.0732,  0.0938,  0.1076],
        [ 0.0458,  0.0664, -0.1922]])

## Comparision operation

In [50]:
x = torch.randint(size=(3,3), low=1, high=10)
y = torch.randint(size=(3,3), low=1, high=10)

In [51]:
# equal
x==y

tensor([[False, False, False],
        [ True, False, False],
        [ True, False, False]])

In [52]:
## greater
x>y

tensor([[False, False,  True],
        [False,  True,  True],
        [False,  True, False]])

In [53]:
# not equal to
x != y

tensor([[ True,  True,  True],
        [False,  True,  True],
        [False,  True,  True]])

## Special function


In [54]:
d = torch.randint(size=(4,4), low =1 , high = 10 , dtype =torch.float32)

In [55]:
## Log
torch.log(d)

tensor([[0.0000, 0.0000, 1.7918, 0.0000],
        [2.1972, 1.6094, 2.0794, 2.1972],
        [1.0986, 1.9459, 0.0000, 1.0986],
        [1.7918, 2.0794, 1.0986, 1.3863]])

In [56]:
## exp
torch.exp(d)

tensor([[2.7183e+00, 2.7183e+00, 4.0343e+02, 2.7183e+00],
        [8.1031e+03, 1.4841e+02, 2.9810e+03, 8.1031e+03],
        [2.0086e+01, 1.0966e+03, 2.7183e+00, 2.0086e+01],
        [4.0343e+02, 2.9810e+03, 2.0086e+01, 5.4598e+01]])

In [57]:
## sigmoid
torch.sigmoid(d)

tensor([[0.7311, 0.7311, 0.9975, 0.7311],
        [0.9999, 0.9933, 0.9997, 0.9999],
        [0.9526, 0.9991, 0.7311, 0.9526],
        [0.9975, 0.9997, 0.9526, 0.9820]])

In [58]:
## relu
torch.relu(d)

tensor([[1., 1., 6., 1.],
        [9., 5., 8., 9.],
        [3., 7., 1., 3.],
        [6., 8., 3., 4.]])

## inplace Operation

In [59]:
g = torch.rand(2,2)
h = torch.rand((2,2))


In [60]:
g+h

tensor([[1.4488, 1.1699],
        [0.8011, 0.6905]])

In [61]:
## if we want to change permanent then we can use any function with _(underscore). --> inplace operation

In [62]:
g.add_(h)

tensor([[1.4488, 1.1699],
        [0.8011, 0.6905]])

In [63]:
g

tensor([[1.4488, 1.1699],
        [0.8011, 0.6905]])

## copying a tensor

In [64]:
c = torch.rand(3,3)
c

tensor([[0.7614, 0.6949, 0.7133],
        [0.3333, 0.4325, 0.7307],
        [0.7065, 0.8321, 0.2001]])

In [65]:
b = a

In [66]:
a[0][1]=0
a

tensor([[0.7041, 0.0000, 0.6959],
        [0.9849, 0.2924, 0.4823],
        [0.6150, 0.4967, 0.4521]])

In [67]:
b
## don't want to change in b

tensor([[0.7041, 0.0000, 0.6959],
        [0.9849, 0.2924, 0.4823],
        [0.6150, 0.4967, 0.4521]])

In [68]:
b = a.clone()

In [69]:
a[1][1]=2
a

tensor([[0.7041, 0.0000, 0.6959],
        [0.9849, 2.0000, 0.4823],
        [0.6150, 0.4967, 0.4521]])

In [70]:
b

tensor([[0.7041, 0.0000, 0.6959],
        [0.9849, 0.2924, 0.4823],
        [0.6150, 0.4967, 0.4521]])

## Tensor operation on GPU

In [71]:

import time

# Define matrix size
size = (1000, 1000)

# Create random matrices
A = torch.rand(size)
B = torch.rand(size)

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# CPU Computation
start_cpu = time.time()
result_cpu = torch.matmul(A, B)  # Matrix multiplication on CPU
end_cpu = time.time()
cpu_time = end_cpu - start_cpu

# Move tensors to GPU
A_gpu = A.to(device)
B_gpu = B.to(device)

# GPU Computation (with torch.cuda.synchronize to ensure timing is accurate)
torch.cuda.synchronize()
start_gpu = time.time()
result_gpu = torch.matmul(A_gpu, B_gpu)  # Matrix multiplication on GPU
torch.cuda.synchronize()
end_gpu = time.time()
gpu_time = end_gpu - start_gpu

# Print time taken
print(f"CPU Time: {cpu_time:.6f} seconds")
print(f"GPU Time: {gpu_time:.6f} seconds" if torch.cuda.is_available() else "GPU not available.")


CPU Time: 0.083008 seconds
GPU Time: 0.152829 seconds


## Reshapeing Tensor

In [75]:
x = torch.ones(4,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [77]:
## reshape
x.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [79]:
## flatten
a.flatten()

tensor([0.7041, 0.0000, 0.6959, 0.9849, 2.0000, 0.4823, 0.6150, 0.4967, 0.4521])

In [81]:
x = torch.rand(1, 3, 1, 4)  # Shape: [1, 3, 1, 4]
print("Original shape:", x.shape)

x_squeezed = torch.squeeze(x)  # Removes all dimensions of size 1
print("Squeezed shape:", x_squeezed.shape)

x_squeezed_dim = torch.squeeze(x, dim=2)  # Removes only dim=2 if size is 1
print("Squeezed (dim=2) shape:", x_squeezed_dim.shape)

Original shape: torch.Size([1, 3, 1, 4])
Squeezed shape: torch.Size([3, 4])
Squeezed (dim=2) shape: torch.Size([1, 3, 4])


## NumPy and Torch

In [82]:
import numpy as np

In [83]:
f = torch.tensor([3,4,5,6,6])
f

tensor([3, 4, 5, 6, 6])

In [85]:
d = f.numpy()
d

array([3, 4, 5, 6, 6])

In [86]:
c = np.array([2,3,4,5])
c

array([2, 3, 4, 5])

In [87]:
torch.from_numpy(c)

tensor([2, 3, 4, 5])